### ISSUE TITLE
New Cars DLC

### ISSUE THREAD

**Issue by Kugelschieber** [Kugelschieber/acweb#37]
Add cars from new DLC. I'm not intending to buy it yet, so some help would be nice. Extracting the new DLC cars and tracks can be done using the tools/extractor.go "script". It's important to add the new cars and tracks, not to delete existing ones. So either the extracting user must have all DLCs or add the cars/tracks manully from the extracted tracks.json/cars.json to the repository.

**Comment by Rolzzz** [comment]
[cars.zip](https://github.com/DeKugelschieber/acweb/files/1404530/cars.zip)
This has all DLC's as well as a few mod cars in my cars list. (229 cars in total)

When I run for tracks I get the following error

2017/10/22 10:52:55 invalid character 'ï' looking for beginning of value
exit status 1

Is there anyway I can see what track is causing this issue? I have 68 tracks (inc a few mod ones)

**Comment by DeKugelschieber** [comment]
The tracks/cars json should only contain official DLCs for acweb and extended with mods for you own needs. So everyone can add the stuff they need.

Your error looks like AC cannot handle the ï character? Maybe one of the tracks you got has a strange name? acweb should be able to handle unicode characters, but I don't know what AC is doing.

**Comment by Kugelschieber** [comment]
I just bought all DLCs, so I'm able to update the config.

**Comment by Kugelschieber** [comment]
Done.
